# Tell Travis CI we're using PHP
language: php

# Currently checking only against latest PHP - PHPCompatibilityWP does linting for earlier versions 
php:
  - 7.3

before_script:
- composer install

script: ./vendor/bin/phpcs -p admin/ includes/ lib/ loader.php --standard=PHPCompatibilityWP --runtime-set testVersion 5.6- --extensions=php
